SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `insona`.`product` ADD COLUMN `driver_id` INT(10) UNSIGNED NOT NULL  AFTER `coverpath` , ADD COLUMN `cover_requirement` CHAR(26) NOT NULL  AFTER `driver_id` ;

CREATE  TABLE IF NOT EXISTS `insona`.`product_download` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT ,
  `product_id` INT(10) UNSIGNED NOT NULL ,
  `title` VARCHAR(100) NOT NULL ,
  `link` VARCHAR(200) NOT NULL ,
  `hidden` TINYINT(3) UNSIGNED NOT NULL ,
  `createline` INT(10) UNSIGNED NOT NULL ,
  `updateline` INT(10) UNSIGNED NOT NULL ,
  PRIMARY KEY (`id`) ,
  INDEX `fk_product_download_product_id_idx` (`product_id` ASC) ,
  CONSTRAINT `fk_product_download_product_id`
    FOREIGN KEY (`product_id` )
    REFERENCES `insona`.`product` (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
