SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `insona`.`user` ADD COLUMN `phone` VARCHAR(20) NOT NULL  AFTER `birthday` , ADD COLUMN `company` VARCHAR(60) NOT NULL  AFTER `phone` , ADD COLUMN `idcard` VARCHAR(20) NOT NULL  AFTER `company` , ADD COLUMN `country` VARCHAR(20) NOT NULL  AFTER `idcard` , ADD COLUMN `city` VARCHAR(20) NOT NULL  AFTER `country` , ADD COLUMN `address` VARCHAR(100) NOT NULL  AFTER `city` , ADD COLUMN `install_type` VARCHAR(60) NOT NULL  AFTER `address` , ADD COLUMN `install_way` VARCHAR(60) NOT NULL  AFTER `install_type` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
