SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE  TABLE IF NOT EXISTS `insona`.`company_member` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT ,
  `email` VARCHAR(100) NOT NULL ,
  `username` VARCHAR(60) NOT NULL ,
  `password` CHAR(40) NOT NULL ,
  `hidden` TINYINT(3) UNSIGNED NOT NULL ,
  `createline` INT(10) UNSIGNED NOT NULL ,
  `birthday` INT(10) UNSIGNED NOT NULL ,
  `phone` VARCHAR(20) NOT NULL ,
  `company` VARCHAR(60) NOT NULL ,
  `idcard` VARCHAR(20) NOT NULL ,
  `country` VARCHAR(20) NOT NULL ,
  `city` VARCHAR(20) NOT NULL ,
  `address` VARCHAR(100) NOT NULL ,
  `install_type` VARCHAR(60) NOT NULL ,
  `install_way` VARCHAR(60) NOT NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

ALTER TABLE `insona`.`user` DROP COLUMN `install_way` , DROP COLUMN `install_type` , DROP COLUMN `address` , DROP COLUMN `city` , DROP COLUMN `country` , DROP COLUMN `idcard` , DROP COLUMN `company` , DROP COLUMN `phone` , DROP COLUMN `birthday` , DROP COLUMN `certificate` , CHANGE COLUMN `username` `username` VARCHAR(20) NOT NULL  
, ADD UNIQUE INDEX `email_UNIQUE` (`email` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
